services:
  imc-ui:
    image: imc-ui:1.0.0
    container_name: imc-ui
    restart: always
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network